### ISSUE TITLE
拿到的token是json的，能读到里面的值吗？

### ISSUE THREAD

**Issue by filicat** [Vgbire/tokencv#1]
![image](https://user-images.githubusercontent.com/43430296/231629989-f421f425-b51f-4f4a-97d3-61ca4d57457d.png)
现在pro__Access-Token能读到json的内容，请问能读到json里面的值吗
pro__Access-Token.value的写法试过了，无法读出值

**Comment by Vgbire** [comment]
目前不可以，但是可以在下一版本提供支持对象类型的读取，类似['outkey','innerkey']这样去读取里面的值
也欢迎提PR

**Comment by filicat** [comment]
> 目前不可以，但是可以在下一版本提供支持对象类型的读取，类似['outkey','innerkey']这样去读取里面的值 也欢迎提PR

好的，谢谢~
